packages:
  - 'packages/*'

catalog:
  rimraf: ^5.0.10
  wait-on: ^8.0.2
  "@semaphore-protocol/contracts": github:jimmychu0807/semaphore#identity-cli&path:/packages/contracts/contracts
  "@semaphore-protocol/group": github:jimmychu0807/semaphore#identity-cli&path:/packages/group
  "@semaphore-protocol/identity": github:jimmychu0807/semaphore#identity-cli&path:/packages/identity
  "@semaphore-protocol/proof": github:jimmychu0807/semaphore#identity-cli&path:/packages/proof
