[profile.default]
evm_version = "cancun"
src = "src"
out = "out"
script = "script"
libs = ["node_modules"]
fs_permissions = [{ access = "read", path = "out-optimized" }, { access = "read-write", path = "gas_calculations" }]
allow_paths = ["*", "/"]
gas_limit = "18446744073709551615"
memory_limit = 2147483648
verbosity = 3
cbor_metadata=true
# via_ir = true
# optimizer = true
# optimizer_runs = 200

[rpc_endpoints]
sepolia = "${ETH_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 100
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
